on:
  push:
    branches:
    - main

jobs:
  my_job:
    name: deploy to production
    runs-on: self-hosted
    steps:
    - run: |
        tmux send -t runnerMessaging:pane C-c
        tmux send -t runnerMessaging:pane "cd ~/messaging" ENTER
        tmux send -t runnerMessaging:pane "git pull" ENTER
        tmux send -t runnerMessaging:pane "export $(cat .env)" ENTER
        tmux send -t runnerMessaging:pane "cd ~/messaging/messaging" ENTER
        tmux send -t runnerMessaging:pane "dotnet ef database update" ENTER
        tmux send -t runnerMessaging:pane "dotnet run ENTER
